import 'producto.dart';

const List<Producto> productosDestacados = [

  Producto(
    id: '6',
    nombre: 'Botines Chelsea',
    precio: 200000.00,
    imagenUrl: 'assets/zapatos_negros.png',
    categoria: 'Hombre',
    tallas: ['39', '40', '41', '42', '43'],
    color: 'Negro',
    descripcion: 'Botines Chelsea clásicos lisos, con paneles elásticos laterales. Diseño versátil para estilos formales o casuales.',
  ),
  Producto(
    id: '7',
    nombre: 'Camisa tipo Polo',
    precio: 100000.00,
    imagenUrl: 'assets/camisa_tipo_polo.png',
    categoria: 'Hombre',
    tallas: ['S', 'M', 'L', 'XL'],
    color: 'Negro',
    descripcion: 'Camisa tipo polo clásica de manga corta en color negro con logo bordado en contraste. Ideal para un look casual y cómodo.',
  ),
  Producto(
    id: '8',
    nombre: 'Botas Timberland',
    precio: 500000.00,
    imagenUrl: 'assets/zapatos_timberland.png',
    categoria: 'Hombre',
    tallas: ['39', '40', '41', '42', '43', '44'],
    color: 'Mostaza',
    descripcion: 'Botas clásicas impermeables, con cuello acolchado oscuro para mayor comodidad y suela de goma con excelente tracción. Ideales para un look casual o de trabajo.',
  ),
  Producto(
    id: '9',
    nombre: 'Pantalón de vestir',
    precio: 100000.00,
    imagenUrl: 'assets/pantalon_de_vestir.png',
    categoria: 'Hombre',
    tallas: ['30', '32', '34', '36', '38'],
    color: 'Negro',
    descripcion: 'Pantalón de vestir formal en color negro con corte recto y pliegue frontal. Ideal para la oficina o eventos elegantes.',
  ),
  Producto(
    id: '10',
    nombre: 'Jean clásico',
    precio: 90000.00,
    imagenUrl: 'assets/blue_jean.png',
    categoria: 'Hombre',
    tallas: ['28', '30', '32', '34', '36', '38'],
    color: 'Azul',
    descripcion: 'Pantalón jean clásico de mezclilla azul con corte recto y diseño tradicional de cinco bolsillos. Un básico indispensable para cualquier estilo casual.',
  ),
  Producto(
    id: '11',
    nombre: 'Gabán Negro',
    precio: 150000.00,
    imagenUrl: 'assets/gaban_negro.png',
    categoria: 'Hombre',
    tallas: ['S', 'M', 'L', 'XL'],
    color: 'Negro',
    descripcion: 'Elegante gabán de vestir en color negro con solapas clásicas y cierre de botones. Perfecto para un estilo formal y sofisticado en climas fríos.',
  ),
  Producto(
    id: '12',
    nombre: 'Tenis blancos',
    precio: 350000.00,
    imagenUrl: 'assets/tenis_blanco.png',
    categoria: 'Hombre',
    tallas: ['39', '40', '41', '42', '43', '44'],
    color: 'Blanco',
    descripcion: 'Zapatillas deportivas clásicas en color blanco puro con detalles perforados en la punta. Un calzado versátil, cómodo y esencial para cualquier estilo urbano o casual.',
  ),
  Producto(
    id: '13',
    nombre: 'Pantalón Vaquero Negro Lavado',
    precio: 100000.00,
    imagenUrl: 'assets/pantalon_vaquero_negro.png',
    categoria: 'Hombre',
    tallas: ['30', '32', '34', '36', '38'],
    color: 'Negro Lavado',
    descripcion: 'Pantalón vaquero de corte ancho y tiro alto en color negro lavado. Presenta un diseño clásico de cinco bolsillos con un ajuste cómodo y relajado. Ideal para un look moderno y casual.',
  ),
  Producto(
    id: '14',
    nombre: 'Chaqueta Bomber de Cuero Sintético',
    precio: 130000.00,
    imagenUrl: 'assets/chaqueta_cuero_bomber.png',
    categoria: 'Hombre',
    tallas: ['S', 'M', 'L', 'XL'],
    color: 'Marrón oscuro',
    descripcion: 'Chaqueta estilo bomber de cuero sintético en color marrón oscuro. Cuenta con un corte holgado, cierre frontal de cremallera, cuello de solapa, y puños y bajo elásticos para un ajuste cómodo y moderno. Perfecta para un look casual y atrevido.',
  ),
  Producto(
    id: '15',
    nombre: 'Camiseta Básica Blanca',
    precio: 40000.00,
    imagenUrl: 'assets/camisa_blanca.png',
    categoria: 'Hombre',
    tallas: ['S', 'M', 'L', 'XL'],
    color: 'Blanco',
    descripcion: 'Camiseta básica de manga corta y cuello redondo en color blanco. Una prenda esencial, cómoda y versátil para el uso diario.',
  ),
  Producto(
    id: '16',
    nombre: 'Chaqueta Universitaria Negra',
    precio: 120000.00,
    imagenUrl: 'assets/chaqueta_negra.png',
    categoria: 'Hombre',
    tallas: ['S', 'M', 'L', 'XL'],
    color: 'Negro',
    descripcion: 'Chaqueta estilo universitaria en color negro con mangas en contraste. Presenta detalles de rayas blancas en el cuello, puños y dobladillo, con cierre frontal de botones a presión.',
  ),
];